### ISSUE TITLE
Please clarify aim and scope

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [boostorg/mincmake#1]
I just cloned this repo and ran CMake.

This appears to fetch a subset of boost source code (good!) and generate some makefiles.

Generated makefiles have some targets but "all" does nothing, most seem build-time test related.

Now what?

Q1: What is the aim of this repo? To help people fetch and compile boost? To help them use automatically Boost from another CMake project?
Q2: Does the project seem to do nothing because it's just an unfinished embryo?

Thanks for clarifying.

**Comment by pdimov** [comment]
I've updated the README to clarify that this repository contains utility functions that are intended to be used by Boost libraries, and is not useful on its own.

At the moment, it enables a Boost library to provide a `check` target in its CMakeLists.txt so that its tests can be ran from CMake. An example of that use can be seen in Mp11 and Assert, see https://github.com/boostorg/mp11/blob/develop/CMakeLists.txt#L19 and https://github.com/boostorg/assert/blob/develop/CMakeLists.txt.

**Comment by fidergo-stephane-gourichon** [comment]
Ah, that's much better. Not what I was looking for, but from now on it is written to enlighten future bypassers. Thanks.
